import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

export const metadata: Metadata = {
  title: "Analyzer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black relative cont px-6 xl:px-0`}>
        <div className="bg-black"></div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
