import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/page';
import Footer from '@/components/footer';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'Analyzer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{ cssLayerName: 'clerk', theme: dark }}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className={`bg-black relative md:px-6 px-4 xl:px-0`}>
          <Header />
          <main className="cont">{children}</main>
          <Analytics />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
