import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/page';
import Footer from '@/components/footer/page';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';

export const metadata: Metadata = {
  title: 'Analyzer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ cssLayerName: 'clerk', theme: dark }}>
      <html lang="en">
        <body className={`bg-black relative cont px-6 xl:px-0`}>
          <div className="bg-black"></div>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
